// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DiagramConvertConfiguration DiagramConvertConfiguration
//
// swagger:model DiagramConvertConfiguration
type DiagramConvertConfiguration struct {

	// diagram.convert.edge
	Edge bool `json:"edge,omitempty"`

	// diagram.convert.node
	Node bool `json:"node,omitempty"`

	// diagram.convert.text
	Text bool `json:"text,omitempty"`
}

// Validate validates this diagram convert configuration
func (m *DiagramConvertConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DiagramConvertConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiagramConvertConfiguration) UnmarshalBinary(b []byte) error {
	var res DiagramConvertConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
