// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DiagramConfiguration DiagramConfiguration
//
// swagger:model DiagramConfiguration
type DiagramConfiguration struct {

	// convert
	Convert *DiagramConvertConfiguration `json:"convert,omitempty"`

	// diagram.enable-sub-blocks
	EnableSubBlocks bool `json:"enable-sub-blocks,omitempty"`

	// text
	Text *TextConfConfiguration `json:"text,omitempty"`
}

// Validate validates this diagram configuration
func (m *DiagramConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConvert(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateText(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DiagramConfiguration) validateConvert(formats strfmt.Registry) error {

	if swag.IsZero(m.Convert) { // not required
		return nil
	}

	if m.Convert != nil {
		if err := m.Convert.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("convert")
			}
			return err
		}
	}

	return nil
}

func (m *DiagramConfiguration) validateText(formats strfmt.Registry) error {

	if swag.IsZero(m.Text) { // not required
		return nil
	}

	if m.Text != nil {
		if err := m.Text.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("text")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DiagramConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiagramConfiguration) UnmarshalBinary(b []byte) error {
	var res DiagramConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
