// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GuidesConfiguration GuidesConfiguration
//
// swagger:model GuidesConfiguration
type GuidesConfiguration struct {

	// text.guides.enable
	Enable bool `json:"enable,omitempty"`
}

// Validate validates this guides configuration
func (m *GuidesConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GuidesConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GuidesConfiguration) UnmarshalBinary(b []byte) error {
	var res GuidesConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
