// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JiixTextConfiguration JiixTextConfiguration
//
// swagger:model JiixTextConfiguration
type JiixTextConfiguration struct {

	// export.jiix.text.chars
	Chars bool `json:"chars,omitempty"`

	// export.jiix.text.words
	Words bool `json:"words,omitempty"`
}

// Validate validates this jiix text configuration
func (m *JiixTextConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JiixTextConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JiixTextConfiguration) UnmarshalBinary(b []byte) error {
	var res JiixTextConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
