// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Recognition Recognition
//
// swagger:model Recognition
type Recognition struct {

	// shape
	Shape bool `json:"shape,omitempty"`

	// text
	Text bool `json:"text,omitempty"`
}

// Validate validates this recognition
func (m *Recognition) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Recognition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Recognition) UnmarshalBinary(b []byte) error {
	var res Recognition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
