// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TextConfConfiguration TextConfConfiguration
//
// swagger:model TextConfConfiguration
type TextConfConfiguration struct {

	// text.configuration.addLKText
	AddLKText bool `json:"addLKText,omitempty"`

	// text.configuration.customLexycon
	CustomLexicon []string `json:"customLexicon"`

	// text.configuration.customResources
	CustomResources []string `json:"customResources"`
}

// Validate validates this text conf configuration
func (m *TextConfConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TextConfConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TextConfConfiguration) UnmarshalBinary(b []byte) error {
	var res TextConfConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
