// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JiixConfiguration JiixConfiguration
//
// swagger:model JiixConfiguration
type JiixConfiguration struct {

	// export.jiix.bounding-box
	BoundingBox bool `json:"bounding-box,omitempty"`

	// export.jiix.strokes
	Strokes bool `json:"strokes,omitempty"`

	// export.jiix.style
	Style bool `json:"style,omitempty"`

	// text
	Text *JiixTextConfiguration `json:"text,omitempty"`
}

// Validate validates this jiix configuration
func (m *JiixConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateText(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JiixConfiguration) validateText(formats strfmt.Registry) error {

	if swag.IsZero(m.Text) { // not required
		return nil
	}

	if m.Text != nil {
		if err := m.Text.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("text")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *JiixConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JiixConfiguration) UnmarshalBinary(b []byte) error {
	var res JiixConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
