// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MarginConfiguration MarginConfiguration
//
// swagger:model MarginConfiguration
type MarginConfiguration struct {

	// math.margin.bottom
	Bottom int32 `json:"bottom,omitempty"`

	// math.margin.left
	Left int32 `json:"left,omitempty"`

	// math.margin.right
	Right int32 `json:"right,omitempty"`

	// math.margin.top
	Top int32 `json:"top,omitempty"`
}

// Validate validates this margin configuration
func (m *MarginConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarginConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarginConfiguration) UnmarshalBinary(b []byte) error {
	var res MarginConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
