// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MathConfiguration MathConfiguration
//
// swagger:model MathConfiguration
type MathConfiguration struct {

	// math.customGrammarContent
	CustomGrammarContent string `json:"customGrammarContent,omitempty"`

	// math.customGrammarId
	CustomGrammarID string `json:"customGrammarId,omitempty"`

	// margin
	Margin *MarginConfiguration `json:"margin,omitempty"`

	// solver
	Solver *SolverConfiguration `json:"solver,omitempty"`
}

// Validate validates this math configuration
func (m *MathConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMargin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSolver(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MathConfiguration) validateMargin(formats strfmt.Registry) error {

	if swag.IsZero(m.Margin) { // not required
		return nil
	}

	if m.Margin != nil {
		if err := m.Margin.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("margin")
			}
			return err
		}
	}

	return nil
}

func (m *MathConfiguration) validateSolver(formats strfmt.Registry) error {

	if swag.IsZero(m.Solver) { // not required
		return nil
	}

	if m.Solver != nil {
		if err := m.Solver.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("solver")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MathConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MathConfiguration) UnmarshalBinary(b []byte) error {
	var res MathConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
