// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RawContentConfiguration RawContentConfiguration
//
// swagger:model RawContentConfiguration
type RawContentConfiguration struct {

	// recognition
	Recognition *Recognition `json:"recognition,omitempty"`

	// text
	Text *TextConfConfiguration `json:"text,omitempty"`
}

// Validate validates this raw content configuration
func (m *RawContentConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRecognition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateText(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RawContentConfiguration) validateRecognition(formats strfmt.Registry) error {

	if swag.IsZero(m.Recognition) { // not required
		return nil
	}

	if m.Recognition != nil {
		if err := m.Recognition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("recognition")
			}
			return err
		}
	}

	return nil
}

func (m *RawContentConfiguration) validateText(formats strfmt.Registry) error {

	if swag.IsZero(m.Text) { // not required
		return nil
	}

	if m.Text != nil {
		if err := m.Text.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("text")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RawContentConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RawContentConfiguration) UnmarshalBinary(b []byte) error {
	var res RawContentConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
