// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StrokeGroup StrokeGroup
//
// a list of strokes that share the same pen style
//
// swagger:model StrokeGroup
type StrokeGroup struct {

	// CSS style for the pen. See https://developer.myscript.com/docs/interactive-ink/latest/reference/web/styling/
	PenStyle string `json:"penStyle,omitempty"`

	// CSS classes for the pen. Classes are to be provided in the general CSS theme. See https://developer.myscript.com/docs/interactive-ink/latest/reference/web/styling/
	PenStyleClasses string `json:"penStyleClasses,omitempty"`

	// a list of strokes
	// Required: true
	Strokes []*Stroke `json:"strokes"`
}

// Validate validates this stroke group
func (m *StrokeGroup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStrokes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StrokeGroup) validateStrokes(formats strfmt.Registry) error {

	if err := validate.Required("strokes", "body", m.Strokes); err != nil {
		return err
	}

	for i := 0; i < len(m.Strokes); i++ {
		if swag.IsZero(m.Strokes[i]) { // not required
			continue
		}

		if m.Strokes[i] != nil {
			if err := m.Strokes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("strokes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *StrokeGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StrokeGroup) UnmarshalBinary(b []byte) error {
	var res StrokeGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
